name: BetterSorcery
version: 0.0.1
main: me.monstuhs.bettersorcery.BetterSorcery
description: Adds meaningful sorcery to Minecraft.
author: monstuhs
commands:
   stats:
      description: Show your currents stats
      usage: /<command>
   dragon:
      description: Spawn ender dragon
      usage: /<command>